const userActionTypes = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  RESET_STATUS: 'RESET_STATUS',
  UPDATE_ISNEW: 'UPDATE_ISNEW',
  UPDATE_USER_ALLERGIES: 'UPDATE_USER_ALLERGIES'
};

export default userActionTypes;
