const bookingActionTypes = {
  SAVE_SELECTION: 'SAVE_SELECTION',
  RESET_BOOKING: 'RESET_BOOKING',
  CREATE_BOOKING: 'CREATE_BOOKING',
  INVITE: 'INVITE',
  GET_BOOKING: 'GET_BOOKING'
};

export default bookingActionTypes;
