const restaurantActionTypes = {
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  FILTER_CATEGORIES: 'FILTER_CATEGORIES',
  LOAD_RESTAURANTS: 'LOAD_RESTAURANTS',
  GET_CATEGORY_RESTAURANTS: 'GET_CATEGORY_RESTAURANTS',
  FILTER_RESTAURANTS: 'FILTER_RESTAURANTS',
  GET_SELECTED_RESTAURANT: 'GET_SELECTED_RESTAURANT'
};

export default restaurantActionTypes
;
